function DecodeMsg(eventCode, hubName, sourceObjectName, sourceRoomName) {
    const messages = {
      M_03_20:  { msg :`${hubName}: smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_21:  { msg :`${hubName}: no smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_22:  { msg :`${hubName}: temperature above the threshold value, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_23:  { msg :`${hubName}: temperature level is back to normal, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_24:  { msg :`${hubName}: hardware failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_25:  { msg :`${hubName}: reset after hardware failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_26:  { msg :`${hubName}: smoke chamber dirty, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_27:  { msg :`${hubName}: smoke chamber clean, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_28:  { msg :`${hubName}: reserve battery low, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_29:  { msg :`${hubName}: reserve battery charged, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_2A:  { msg :`${hubName}: rapid temperature rise detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_2B:  { msg :`${hubName}: rapid temperature rise stopped, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_2C:  { msg :`${hubName}: detector is faulty, ${sourceObjectName} in ${sourceRoomName}. Please, contact the service center listed on the warranty card`, level : "info"},
      M_03_2D:  { msg :`${hubName}: smoke chamber is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_2E:  { msg :`${hubName}: signs of smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_2F:  { msg :`${hubName}: no smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_32:  { msg :`${hubName}: signs of exceeding the temperature threshold detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_33:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_34:  { msg :`${hubName}: signs of rapid temperature rise detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_35:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_03_38:  { msg :`${hubName}: alarm is temporarily muted by pressing on the detector, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      //general
      M_21_00:  { msg :`${sourceObjectName}: external power failure`, level : "info"},
      M_21_01:  { msg :`${sourceObjectName}: external power restored`, level : "info"},
      M_21_02:  { msg :`${sourceObjectName}: battery low`, level : "info"},
      M_21_03:  { msg :`${sourceObjectName}: battery charged`, level : "info"},
      M_21_04:  { msg :`${sourceObjectName}: hub lid is open`, level : "info"},
      M_21_05:  { msg :`${sourceObjectName}: hub lid is closed`, level : "info"},
      M_21_06:  { msg :`${sourceObjectName}: cellular signal strength is poor`, level : "info"},
      M_21_07:  { msg :`${sourceObjectName}: cellular signal strength is OK`, level : "info"},
      M_21_08:  { msg :`${sourceObjectName}: high level of interference at Jeweller frequencies`, level : "info"},
      M_21_09:  { msg :`${sourceObjectName}: interference level at Jeweller frequencies is OK`, level : "info"},
      M_21_0A:  { msg :`${sourceObjectName}: hub is offline. Check the network connection.`, level : "info"},
      M_21_0B:  { msg :`${sourceObjectName}: hub is online again`, level : "info"},
      M_21_0C:  { msg :`${sourceObjectName} was switched off`, level : "info"},
      M_21_0D:  { msg :`${sourceObjectName} was switched on`, level : "info"},
      M_21_0E:  { msg :`${sourceObjectName} was reset to factory settings`, level : "info"},
      M_21_10:  { msg :`${sourceObjectName}: updating firmware…`, level : "info"},
      M_21_11:  { msg :`${sourceObjectName}: firmware updated`, level : "info"},
      M_21_12:  { msg :`${sourceObjectName}: malfunction detected`, level : "info"},
      M_21_13:  { msg :`${sourceObjectName}: connection to the monitoring station is lost. Check cellular signal strength and the Ethernet port on the hub`, level : "info"},
      M_21_15:  { msg :`${sourceObjectName}: backup battery is disconnected`, level : "info"},
      M_21_16:  { msg :`${sourceObjectName}: backup battery is connected`, level : "info"},
      M_21_17:  { msg :`${hubName}: high level of interference at Wings frequencies`, level : "info"},
      M_21_18:  { msg :`${hubName}: interference level at Wings frequencies is OK`, level : "info"},
      M_21_19:  { msg :`Data source for import has been selected`, level : "info"},
      M_21_1A:  { msg :`New hub to import data has been selected`, level : "info"},
      M_21_1B:  { msg :`Data import has been started`, level : "info"},
      M_21_1C:  { msg :`Data import has been completed`, level : "info"},
      M_21_1D:  { msg :`Data import has been completed. Some devices have not been transferred, please pair them manually.`, level : "info"},
      M_21_1E:  { msg :`${hubName}: intrusion alarm is confirmed`, level : "info"},
      M_21_1F:  { msg :`${hubName}: hold-up alarm is confirmed`, level : "info"},
      M_21_20:  { msg :`${sourceObjectName}: server connection via Ethernet lost`, level : "info"},
      M_21_21:  { msg :`${sourceObjectName}: server connection via Ethernet restored`, level : "info"},
      M_21_22:  { msg :`${sourceObjectName}: server connection via cellular lost`, level : "info"},
      M_21_23:  { msg :`${sourceObjectName}: server connection via cellular restored`, level : "info"},
      M_21_24:  { msg :`${sourceObjectName}: server connection via Wi-Fi lost`, level : "info"},
      M_21_25:  { msg :`${sourceObjectName}: server connection via Wi-Fi restored`, level : "info"},
      M_21_26:  { msg :`${hubName}: short-circuit failure on the lines`, level : "info"},
      M_21_27:  { msg :`${hubName}: lines restored after a short circuit`, level : "info"},
      M_21_28:  { msg :`${hubName}: signal lines overvoltage failure`, level : "info"},
      M_21_29:  { msg :`${hubName}: signal lines restored after overvoltage failure`, level : "info"},
      M_22_00:  { msg :`${hubName}: disarmed by ${sourceObjectName}`, level : "info"},
      M_22_01:  { msg :`${hubName}: armed by ${sourceObjectName}`, level : "info"},
      M_22_02:  { msg :`${hubName}: night mode activated by ${sourceObjectName}`, level : "info"},
      M_22_03:  { msg :`${hubName}: ${sourceObjectName} pressed the panic button`, level : "info"},
      M_22_07:  { msg :`${hubName}: new user ${sourceObjectName} added`, level : "info"},
      M_22_08:  { msg :`${hubName}: user ${sourceObjectName} removed`, level : "info"},
      M_22_09:  { msg :`${sourceRoomName} granted the access to hub settings to ${sourceObjectName} (%4$s) for hubName hours`, level : "info"},
      M_22_0A:  { msg :`${sourceRoomName} has allowed permanent access to the hub settings to ${sourceObjectName} (%4$s)`, level : "info"},
      M_22_0B:  { msg :`${sourceRoomName} has denied ${sourceObjectName} (%4$s) access request to the hub settings`, level : "info"},
      M_22_0D:  { msg :`Request for hub settings access received`, level : "info"},
      M_22_20:  { msg :`${hubName}: ${sourceObjectName} pressed the panic button`, level : "info"},
      M_22_24:  { msg :`${hubName}: unsuccessful arming attempt by ${sourceObjectName}`, level : "info"},
      M_22_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt by ${sourceObjectName}`, level : "info"},
      M_22_26:  { msg :`${hubName}: armed with malfunctions by ${sourceObjectName}`, level : "info"},
      M_22_27:  { msg :`${hubName}: night mode activated with malfunctions by ${sourceObjectName}`, level : "info"},
      M_22_28:  { msg :`${hubName}: night mode deactivated by ${sourceObjectName}`, level : "info"},
      M_22_29:  { msg :`${hubName}: ${sourceRoomName} disarmed by ${sourceObjectName}`, level : "info"},
      M_22_2A:  { msg :`${hubName}: ${sourceRoomName} armed by ${sourceObjectName}`, level : "info"},
      M_22_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions by ${sourceObjectName}`, level : "info"},
      M_22_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt by ${sourceObjectName}`, level : "info"},
      M_22_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed by ${sourceObjectName}`, level : "info"},
      M_22_2F_company:  { msg :`${hubName}: ${sourceRoomName} disarmed under duress by ${sourceObjectName}`, level : "info"},
      M_22_31:  { msg :`${hubName}: disarmed by ${sourceObjectName}`, level : "info"},
      M_22_31_company:  { msg :`${hubName}: disarmed under duress by ${sourceObjectName}`, level : "info"},
      M_22_32:  { msg :`${hubName}: night mode deactivated by ${sourceObjectName}`, level : "info"},
      M_22_32_company:  { msg :`${hubName}: Night mode deactivated under duress by ${sourceObjectName}`, level : "info"},
      M_22_33:  { msg :`${hubName}: arming attempt by ${sourceObjectName} is not complete`, level : "info"},
      M_22_34:  { msg :`${hubName}: ${sourceObjectName} requested system restoration after alarm`, level : "info"},
      M_22_35:  { msg :`${hubName}: ${sourceObjectName} denied request for system restore after alarm. Installer visit is required.`, level : "info"},
      M_22_36:  { msg :`${hubName}: alarm is temporarily muted by ${sourceObjectName}`, level : "info"},
      M_22_37:  { msg :`${hubName}: system is restored after alarms by ${sourceObjectName}`, level : "info"},
      M_22_38:  { msg :`${hubName}: Chime activated by ${sourceObjectName}`, level : "info"},
      M_22_39:  { msg :`${hubName}: Chime deactivated by ${sourceObjectName}`, level : "info"},
      M_22_3A:  { msg :`${hubName}: Chime in ${sourceRoomName} activated by ${sourceObjectName}`, level : "info"},
      M_22_3B:  { msg :`${hubName}: Chime in ${sourceRoomName} deactivated by ${sourceObjectName}`, level : "info"},
      M_22_3C:  { msg :`${sourceRoomName} granted the access to hub settings to ${sourceObjectName} (%4$s) for hubName hours`, level : "info"},
      M_22_3D:  { msg :`${sourceRoomName} has allowed permanent access to the hub settings to ${sourceObjectName} (%4$s)`, level : "info"},
      M_22_3E:  { msg :`${sourceRoomName} has denied ${sourceObjectName} (%4$s) access request to the hub settings`, level : "info"},
      M_22_3F:  { msg :`${hubName}: photo on demand feature enabled for this hub by ${sourceObjectName}`, level : "info"},
      M_22_40:  { msg :`${hubName}: photo on demand feature disabled by ${sourceObjectName}`, level : "info"},
      M_22_41:  { msg :`${hubName}: photo by alarm scenarios feature enabled for this hub by ${sourceObjectName}`, level : "info"},
      M_22_42:  { msg :`${hubName}: photo by alarm scenarios feature disabled by ${sourceObjectName}`, level : "info"},
      M_22_43:  { msg :`${hubName}: unsuccessful arming attempt by ${sourceObjectName}`, level : "info"},
      M_22_44:  { msg :`${hubName}: new time zone ${sourceRoomName} set by %4$s`, level : "info"},
      M_23_08:  { msg :`${hubName}: new group ${sourceObjectName} added`, level : "info"},
      M_23_09:  { msg :`${hubName}: group ${sourceObjectName} removed`, level : "info"},
      M_24_08:  { msg :`${hubName}: new room ${sourceRoomName} added`, level : "info"},
      M_24_09:  { msg :`${hubName}: room ${sourceRoomName} removed`, level : "info"},
      M_25_08:  { msg :`${hubName}: camera ${sourceObjectName} added successfully`, level : "info"},
      M_25_09:  { msg :`${hubName}: camera ${sourceObjectName} removed`, level : "info"},
      M_26_00:  { msg :`${hubName}: lid is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_01:  { msg :`${hubName}: lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_0A:  { msg :`${hubName}: device deactivated, ${sourceObjectName} in ${sourceRoomName}. The device will neither execute commands of the system nor notify about alarms or any other events`, level : "info"},
      M_26_0B:  { msg :`${hubName}: the device is active again, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_0E:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_0F:  { msg :`${hubName}: deactivated automatically by the expiration of the restoration timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_10:  { msg :`${hubName}: restored after automatic deactivation, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_14:  { msg :`${hubName}: restored after automatic deactivation, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_20:  { msg :`${hubName}: alarm is detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_21:  { msg :`${hubName}: recovered after alarm, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_22:  { msg :`${hubName}: alarm detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_23:  { msg :`${hubName}: external contact is shorted out, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_24:  { msg :`${hubName}: external contact is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_26_25:  { msg :`${hubName}: external contact is damaged, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_00:  { msg :`${hubName}: lid is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_01:  { msg :`${hubName}: lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_04:  { msg :`${hubName}: connection lost, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_05:  { msg :`${hubName}: connection restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_0A:  { msg :`${hubName}: device deactivated, ${sourceObjectName} in ${sourceRoomName}. The device will neither execute commands of the system nor notify about alarms or any other events`, level : "info"},
      M_28_0B:  { msg :`${hubName}: the device is active again, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_0C:  { msg :`${hubName}: notifications about the state of the lid are disabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_0D:  { msg :`${hubName}: notifications about the state of the lid are enabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_0E:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_0F:  { msg :`${hubName}: deactivated automatically by the expiration of the restoration timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_14:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_28_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_28_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_28_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_28_23:  { msg :`${hubName}: panic button pressed on ${sourceObjectName}`, level : "info"},
      M_28_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_28_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_28_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_28_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_28_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_28_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_28_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_28_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_28_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_28_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_28_30:  { msg :`${hubName}: attempt to break the password on ${sourceObjectName}`, level : "info"},
      M_28_31:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_28_32:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_28_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_29_08:  { msg :`${hubName}: new key ${sourceObjectName} added`, level : "info"},
      M_29_09:  { msg :`${hubName}: key ${sourceObjectName} removed`, level : "info"},
      M_29_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_29_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_29_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_29_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_29_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_29_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_29_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_29_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_29_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_29_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_29_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_29_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_29_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_2A_08:  { msg :`${hubName}: new scenario ${sourceObjectName} added`, level : "info"},
      M_2A_09:  { msg :`${hubName}: scenario ${sourceObjectName} removed`, level : "info"},
      M_2A_20:  { msg :`${hubName}: disarmed automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_21:  { msg :`${hubName}: armed automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_22:  { msg :`${hubName}: night mode activated automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_24:  { msg :`${hubName}: unsuccessful arming attempt, scenario ${sourceObjectName}`, level : "info"},
      M_2A_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt, scenario ${sourceObjectName}`, level : "info"},
      M_2A_26:  { msg :`${hubName}: armed with malfunctions automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_27:  { msg :`${hubName}: night mode activated with malfunctions automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_28:  { msg :`${hubName}: night mode deactivated automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_29:  { msg :`${hubName}: ${sourceRoomName} disarmed automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_2A:  { msg :`${hubName}: ${sourceRoomName} armed automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions automatically, scenario ${sourceObjectName}`, level : "info"},
      M_2A_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt, scenario ${sourceObjectName}`, level : "info"},
      M_2A_33:  { msg :`${hubName}: scenario ${sourceObjectName} was not executed, arming process was in progress`, level : "info"},
      M_2A_43:  { msg :`${hubName}: unsuccessful arming attempt, scenario ${sourceObjectName}`, level : "info"},
      M_2B_40:  { msg :`Security company ${sourceObjectName} is now monitoring your hub`, level : "info"},
      M_2B_41:  { msg :`Security company ${sourceObjectName} no longer monitors your hub`, level : "info"},
      M_2E_08:  { msg :`${hubName}: device ${sourceObjectName} added successfully`, level : "info"},
      M_2E_09:  { msg :`${hubName}: device ${sourceObjectName} removed`, level : "info"},
      M_2E_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_2E_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_2E_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_2E_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_2E_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_2E_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_2E_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_2E_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_2E_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_2E_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_2E_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_2E_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_2E_33:  { msg :`${hubName}: arming attempt using ${sourceObjectName} is incomplete`, level : "info"},
      M_2E_35:  { msg :`${hubName}: the device ${sourceObjectName} is deactivated. Now it cannot manage security modes.`, level : "info"},
      M_2E_36:  { msg :`${hubName}: device ${sourceObjectName} is active again`, level : "info"},
      M_2E_37:  { msg :`${hubName}: attempt to use temporary deactivated device ${sourceObjectName}`, level : "info"},
      M_2E_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_2F_40:  { msg :`${sourceObjectName} added installation company ${sourceRoomName} to hub`, level : "info"},
      M_2F_41:  { msg :`${sourceObjectName} deleted installation company ${sourceRoomName} from hub`, level : "info"},
      M_2F_42:  { msg :`Request for hub settings temporary access received`, level : "info"},
      M_2F_43:  { msg :`Request for hub settings permanent access received`, level : "info"},
      M_30_08:  { msg :`${hubName}: access code ${sourceObjectName} added successfully`, level : "info"},
      M_30_09:  { msg :`${hubName}: access code ${sourceObjectName} removed`, level : "info"},
      M_30_20:  { msg :`${hubName}: disarmed with access code ${sourceObjectName}`, level : "info"},
      M_30_21:  { msg :`${hubName}: armed with access code ${sourceObjectName}`, level : "info"},
      M_30_22:  { msg :`${hubName}: night mode activated with access code ${sourceObjectName}`, level : "info"},
      M_30_24:  { msg :`${hubName}: unsuccessful arming attempt with access code ${sourceObjectName}`, level : "info"},
      M_30_25:  { msg :`${hubName}: unsuccessful Night mode activation with access code ${sourceObjectName}`, level : "info"},
      M_30_26:  { msg :`${hubName}: armed with malfunctions using access code ${sourceObjectName}`, level : "info"},
      M_30_27:  { msg :`${hubName}: night mode activated with malfunctions using access code ${sourceObjectName}`, level : "info"},
      M_30_28:  { msg :`${hubName}: night mode deactivated with access code ${sourceObjectName}`, level : "info"},
      M_30_29:  { msg :`${hubName}: ${sourceRoomName} disarmed with access code ${sourceObjectName}`, level : "info"},
      M_30_2A:  { msg :`${hubName}: ${sourceRoomName} armed with access code ${sourceObjectName}`, level : "info"},
      M_30_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using access code ${sourceObjectName}`, level : "info"},
      M_30_2E:  { msg :`${hubName}: ${sourceRoomName} unsuccessful arming attempt with access code ${sourceObjectName}`, level : "info"},
      M_30_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed with access code ${sourceObjectName}`, level : "info"},
      M_30_2F_company:  { msg :`${hubName}: ${sourceRoomName} disarmed under duress with access code ${sourceObjectName}`, level : "info"},
      M_30_31:  { msg :`${hubName}: disarmed with access code ${sourceObjectName}`, level : "info"},
      M_30_31_company:  { msg :`${hubName}: disarmed under duress with access code ${sourceObjectName}`, level : "info"},
      M_30_32:  { msg :`${hubName}: night mode deactivated with access code ${sourceObjectName}`, level : "info"},
      M_30_32_company:  { msg :`${hubName}: night mode deactivated under duress with access code ${sourceObjectName}`, level : "info"},
      M_30_33:  { msg :`${hubName}: arming attempt with access code ${sourceObjectName} is incomplete`, level : "info"},
      M_30_35:  { msg :`${hubName}: access code ${sourceObjectName} is deactivated. Now it cannot manage security modes.`, level : "info"},
      M_30_36:  { msg :`${hubName}: access code ${sourceObjectName} is active again`, level : "info"},
      M_30_43:  { msg :`${hubName}: unsuccessful arming attempt with access code ${sourceObjectName}`, level : "info"},
      M_40_04:  { msg :`${sourceObjectName}: NVR lid is open`, level : "info"},
      M_40_05:  { msg :`${sourceObjectName}: NVR lid is closed`, level : "info"},
      M_40_0A:  { msg :`${sourceObjectName}: NVR is offline. Check the network connection.`, level : "info"},
      M_40_0B:  { msg :`${sourceObjectName}: NVR is back online`, level : "info"},
      M_40_20:  { msg :`${hubName}: video scenario %5$s executed`, level : "info"},
      M_40_21:  { msg :`${hubName}: received full video on alarm scenario %5$s`, level : "info"},
      M_41_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_41_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_41_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_41_23:  { msg :`${hubName}: panic button pressed on ${sourceObjectName}`, level : "info"},
      M_41_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_41_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_41_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_41_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_41_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_41_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_41_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_41_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_41_2E:  { msg :`${hubName}: ${sourceRoomName}, unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_41_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_41_2F_company:  { msg :`${hubName}: ${sourceRoomName} disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_41_30:  { msg :`${hubName}: unauthorized access attempt using ${sourceObjectName}`, level : "info"},
      M_41_31:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_41_31_company:  { msg :`${hubName}: disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_41_32:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_41_32_company:  { msg :`${hubName}: Night mode deactivated under duress using ${sourceObjectName}`, level : "info"},
      M_41_33:  { msg :`${hubName}: arming attempt using ${sourceObjectName} is incomplete`, level : "info"},
      M_41_34:  { msg :`${hubName}: alarm is temporarily muted using ${sourceObjectName}`, level : "info"},
      M_41_35:  { msg :`${hubName}: fire emergency button pressed on ${sourceObjectName}`, level : "info"},
      M_41_36:  { msg :`${hubName}: medical help emergency button pressed on ${sourceObjectName}`, level : "info"},
      M_41_37:  { msg :`M_41_37`, level : "info"},
      M_41_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_41_44:  { msg :`${hubName}: connection via Wings channel lost, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_41_45:  { msg :`${hubName}: restored connection via Wings channel, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_42_0A:  { msg :`${hubName}: device deactivated, ${sourceObjectName} in ${sourceRoomName}. The device will neither execute commands of the system nor notify about alarms or any other events`, level : "info"},
      M_42_0B:  { msg :`${hubName}: the device is active again, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_42_20:  { msg :`${hubName}: hold-up device is pressed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_42_21:  { msg :`${hubName}: hold-up device is pressed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_43_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_43_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_43_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_43_23:  { msg :`${hubName}: panic button pressed on ${sourceObjectName}`, level : "info"},
      M_43_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_43_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_43_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_43_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_43_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_43_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_43_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_43_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_43_2E:  { msg :`${hubName}: ${sourceRoomName}, unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_43_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_43_2F_company:  { msg :`${hubName}: ${sourceRoomName} disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_43_30:  { msg :`${hubName}: unauthorized access attempt using ${sourceObjectName}`, level : "info"},
      M_43_31:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_43_31_company:  { msg :`${hubName}: disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_43_32:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_43_32_company:  { msg :`${hubName}: Night mode deactivated under duress using ${sourceObjectName}`, level : "info"},
      M_43_33:  { msg :`${hubName}: arming attempt using ${sourceObjectName} is incomplete`, level : "info"},
      M_43_34:  { msg :`${hubName}: alarm is temporarily muted using ${sourceObjectName}`, level : "info"},
      M_43_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_44_20:  { msg :`${hubName}: overheating, ${sourceObjectName} in ${sourceRoomName}. Touch button of the device is blocked.`, level : "info"},
      M_44_21:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_44_24:  { msg :`${hubName}: failed to execute command, ${sourceObjectName} in ${sourceRoomName}. The device may have malfunctioned. Please contact the support service.`, level : "info"},
      M_44_25:  { msg :`${hubName}: maximum device load exceeded, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_44_28:  { msg :`${hubName}: insufficient power supply, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_44_2C:  { msg :`${hubName}: not responding, ${sourceObjectName} in ${sourceRoomName}. Please check the connectivity with the hub.`, level : "info"},
      M_44_2D:  { msg :`${hubName}: ${sourceObjectName} turned on by %4$s`, level : "info"},
      M_44_2E:  { msg :`${hubName}: ${sourceObjectName} turned on with device touch button`, level : "info"},
      M_44_2F:  { msg :`${hubName}: ${sourceObjectName} turned on, scenario %5$s`, level : "info"},
      M_44_30:  { msg :`${hubName}: ${sourceObjectName} turned on by arming`, level : "info"},
      M_44_31:  { msg :`${hubName}: ${sourceObjectName} turned on by disarming`, level : "info"},
      M_44_32:  { msg :`${hubName}: ${sourceObjectName} turned on`, level : "info"},
      M_44_33:  { msg :`${hubName}: ${sourceObjectName} turned off by %4$s`, level : "info"},
      M_44_34:  { msg :`${hubName}: ${sourceObjectName} turned off with device touch button`, level : "info"},
      M_44_35:  { msg :`${hubName}: ${sourceObjectName} turned off, scenario %5$s`, level : "info"},
      M_44_36:  { msg :`${hubName}: ${sourceObjectName} turned off automatically on timer`, level : "info"},
      M_44_37:  { msg :`${hubName}: ${sourceObjectName} turned off by arming`, level : "info"},
      M_44_38:  { msg :`${hubName}: ${sourceObjectName} turned off by disarming`, level : "info"},
      M_44_39:  { msg :`${hubName}: ${sourceObjectName} turned off`, level : "info"},
      M_45_20:  { msg :`${hubName}: external power failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_45_21:  { msg :`${hubName}: external power restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_45_22:  { msg :`${hubName}: battery has been disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_45_23:  { msg :`${hubName}: battery has been connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_45_2C:  { msg :`${hubName}: not responding, ${sourceObjectName} in ${sourceRoomName}. Please check the connectivity with the hub.`, level : "info"},
      M_46_20:  { msg :`${hubName}: external power failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_46_21:  { msg :`${hubName}: external power restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_46_22:  { msg :`${hubName}: high level of interference at Jeweller frequencies, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_46_23:  { msg :`${hubName}: interference level at Jeweller frequencies is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_46_30:  { msg :`${hubName}: lost connection via photo transmitting channel, ${sourceObjectName} in ${sourceRoomName}. You won’t receive photos from motion detectors connected through range extender.`, level : "info"},
      M_46_31:  { msg :`${hubName}: restored connection via photo transmitting channel, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_46_32:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is offline`, level : "info"},
      M_46_33:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is online again`, level : "info"},
      M_47_20:  { msg :`${hubName}: temperature value is higher than the comfort one, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_21:  { msg :`${hubName}: temperature value is lower than the comfort one, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_22:  { msg :`${hubName}: temperature value is back to comfort, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_23:  { msg :`${hubName}: humidity value is higher than the comfort one, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_24:  { msg :`${hubName}: humidity value is lower than the comfort one, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_25:  { msg :`${hubName}: humidity value is back to comfort, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_26:  { msg :`${hubName}: CO₂ value is higher than the acceptable level, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_27:  { msg :`${hubName}: CO₂ value is back to normal, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_28:  { msg :`${hubName}: device was moved, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_29:  { msg :`${hubName}: some device sensors are faulty, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_2A:  { msg :`${hubName}: all device sensors are OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_30:  { msg :`${hubName}: connection via Wings channel lost, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_47_31:  { msg :`${hubName}: restored connection via Wings channel, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_20:  { msg :`${hubName}: external power failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_21:  { msg :`${hubName}: external power restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_22:  { msg :`${hubName}: temperature is out of range, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_23:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_24:  { msg :`${hubName}: valve stuck, ${sourceObjectName} in ${sourceRoomName}. Check user guide to fix the malfunction.`, level : "info"},
      M_48_29:  { msg :`${hubName}: batteries are not installed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_2A:  { msg :`${hubName}: batteries installed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_2C:  { msg :`${hubName}: not responding, ${sourceObjectName} in ${sourceRoomName}. Please check the connectivity with the hub.`, level : "info"},
      M_48_2E:  { msg :`${hubName}: water supply turned on with device button, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_2F:  { msg :`${hubName}: water supply turned off with device button, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_33:  { msg :`${hubName}: water supply turned on by scenario %5$s, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_34:  { msg :`${hubName}: water supply turned on by arming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_35:  { msg :`${hubName}: water supply turned on by disarming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_36:  { msg :`${hubName}: water supply turned on, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_37:  { msg :`${hubName}: water supply turned on by %4$s, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_38:  { msg :`${hubName}: water supply turned off by scenario %5$s, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_39:  { msg :`${hubName}: water supply turned off by arming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_40:  { msg :`${hubName}: water supply turned off by disarming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_41:  { msg :`${hubName}: water supply turned off, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_48_46:  { msg :`${hubName}: water supply turned off by %4$s, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_20:  { msg :`${hubName}: overheating shutdown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_21:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_22:  { msg :`${hubName}: switched on, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_23:  { msg :`${hubName}: switched off, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_24:  { msg :`${hubName}: unable to perform an action, ${sourceObjectName} in ${sourceRoomName}. The device may have failed. Please contact the support service.`, level : "info"},
      M_4C_26:  { msg :`${hubName}: overcurrent shutdown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_27:  { msg :`${hubName}: current is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_28:  { msg :`${hubName}: overvoltage shutdown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_29:  { msg :`${hubName}: low voltage shutdown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_2A:  { msg :`${hubName}: voltage is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_2C:  { msg :`${hubName}: not responding, ${sourceObjectName} in ${sourceRoomName}. Please check the connectivity with the hub.`, level : "info"},
      M_4C_2D:  { msg :`${hubName}: temporary activated in pulse mode, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_2E:  { msg :`${hubName}: switched on with device button, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_2F:  { msg :`${hubName}: switched off with device button, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_30:  { msg :`${hubName}: temporary activated with device button in pulse mode, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_31:  { msg :`${hubName}: wire sparking detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_33:  { msg :`${hubName}: switched on ${sourceObjectName} in ${sourceRoomName}, scenario %5$s`, level : "info"},
      M_4C_34:  { msg :`${hubName}: switched on by arming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_35:  { msg :`${hubName}: switched on by disarming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_36:  { msg :`${hubName}: switched on, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_37:  { msg :`${hubName}: switched on ${sourceObjectName} in ${sourceRoomName} by %4$s`, level : "info"},
      M_4C_38:  { msg :`${hubName}: switched off ${sourceObjectName} in ${sourceRoomName}, scenario %5$s`, level : "info"},
      M_4C_39:  { msg :`${hubName}: switched off by arming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_40:  { msg :`${hubName}: switched off by disarming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_41:  { msg :`${hubName}: switched off, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_42:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} activated in pulse mode, scenario %5$s`, level : "info"},
      M_4C_43:  { msg :`${hubName}: activated in pulse mode by arming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_44:  { msg :`${hubName}: activated in pulse mode by disarming, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_45:  { msg :`${hubName}: activated in pulse mode, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4C_46:  { msg :`${hubName}: switched off ${sourceObjectName} in ${sourceRoomName} by %4$s`, level : "info"},
      M_4C_47:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} activated in pulse mode by %4$s`, level : "info"},
      M_4C_48:  { msg :`${hubName}: switched off automatically on timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      //smoke
      M_4D_20:  { msg :`${hubName}: smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_21:  { msg :`${hubName}: no smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_22:  { msg :`${hubName}: temperature above the threshold value, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_23:  { msg :`${hubName}: temperature level is back to normal, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_24:  { msg :`${hubName}: malfunction detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_25:  { msg :`${hubName}: malfunction resolved, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_2A:  { msg :`${hubName}: rapid temperature rise detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_2B:  { msg :`${hubName}: rapid temperature rise stopped, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_2C:  { msg :`${hubName}: smoke chamber of detector is faulty, ${sourceObjectName} in ${sourceRoomName}. Please, contact the service center listed on the warranty card.`, level : "info"},
      M_4D_2D:  { msg :`${hubName}: smoke chamber of detector is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_2E:  { msg :`${hubName}: signs of smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_2F:  { msg :`${hubName}: no smoke detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_30:  { msg :`${hubName}: carbon monoxide (СО) detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_31:  { msg :`${hubName}: carbon monoxide (CO) level is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_32:  { msg :`${hubName}: signs of exceeding the temperature threshold detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_33:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_34:  { msg :`${hubName}: signs of rapid temperature rise detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_35:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_36:  { msg :`${hubName}: signs of high CO level detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_37:  { msg :`${hubName}: CO level is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_38:  { msg :`${hubName}: alarm is temporarily muted by pressing on the detector, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_39:  { msg :`${hubName}: critical carbon monoxide (CO) level detected, ${sourceObjectName} in ${sourceRoomName}. Leave the premises immediately.`, level : "info"},
      M_4D_3A:  { msg :`${hubName}: carbon monoxide (CO) level has decreased, ${sourceObjectName} in ${sourceRoomName}. You can return to the premises if necessary.`, level : "info"},
      M_4D_3B:  { msg :`${hubName}: device CO sensor is faulty, ${sourceObjectName} in ${sourceRoomName}. Please, contact the service center listed on the warranty card.`, level : "info"},
      M_4D_3C:  { msg :`${hubName}: device CO sensor is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_4D_3D:  { msg :`${hubName}: device temperature sensor is faulty, ${sourceObjectName} in ${sourceRoomName}. Please, contact the service center listed on the warranty card.`, level : "info"},
      M_4D_3E:  { msg :`${hubName}: device temperature sensor is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
  
      M_53_08:  { msg :`${hubName}: ring connection ${sourceObjectName}:%4$s added`, level : "info"},
      M_53_09:  { msg :`${hubName}: ring connection ${sourceObjectName}:%4$s deleted`, level : "info"},
      M_53_0A:  { msg :`${hubName}: ring ${sourceObjectName}:%4$s disconnected`, level : "info"},
      M_53_0B:  { msg :`${hubName}: ring ${sourceObjectName}:%4$s connected back`, level : "info"},
      M_53_0C:  { msg :`${hubName}: malfunction on ring ${sourceObjectName}:%4$s detected`, level : "info"},
      M_53_0D:  { msg :`${hubName}: ring ${sourceObjectName}:%4$s restored after malfunction`, level : "info"},
      M_61_00:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_01:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_20:  { msg :`${hubName}: opening detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_21:  { msg :`${hubName}: closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_22:  { msg :`${hubName}: external contact is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_23:  { msg :`${hubName}: external contact closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_34:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_61_35:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_62_20:  { msg :`${hubName}: motion detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_00:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_01:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_20:  { msg :`${hubName}: glass break detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_22:  { msg :`${hubName}: external contact is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_23:  { msg :`${hubName}: external contact closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_34:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_64_35:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_68_20:  { msg :`${hubName}: motion detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_68_21:  { msg :`${hubName}: glass break detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6A_20:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_6A_21:  { msg :`${hubName}: armed using ${sourceObjectName}`, level : "info"},
      M_6A_22:  { msg :`${hubName}: night mode activated using ${sourceObjectName}`, level : "info"},
      M_6A_23:  { msg :`${hubName}: panic button pressed on ${sourceObjectName}`, level : "info"},
      M_6A_24:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_6A_25:  { msg :`${hubName}: unsuccessful Night mode activation attempt using ${sourceObjectName}`, level : "info"},
      M_6A_26:  { msg :`${hubName}: armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_6A_27:  { msg :`${hubName}: night mode activated with malfunctions using ${sourceObjectName}`, level : "info"},
      M_6A_28:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_6A_29:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_6A_2A:  { msg :`${hubName}: ${sourceRoomName} armed using ${sourceObjectName}`, level : "info"},
      M_6A_2D:  { msg :`${hubName}: ${sourceRoomName} armed with malfunctions using ${sourceObjectName}`, level : "info"},
      M_6A_2E:  { msg :`${hubName}: ${sourceRoomName}, unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_6A_2F:  { msg :`${hubName}: ${sourceRoomName} disarmed using ${sourceObjectName}`, level : "info"},
      M_6A_2F_company:  { msg :`${hubName}: ${sourceRoomName} disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_6A_30:  { msg :`${hubName}: unauthorized access attempt using ${sourceObjectName}`, level : "info"},
      M_6A_31:  { msg :`${hubName}: disarmed using ${sourceObjectName}`, level : "info"},
      M_6A_31_company:  { msg :`${hubName}: disarmed under duress using ${sourceObjectName}`, level : "info"},
      M_6A_32:  { msg :`${hubName}: night mode deactivated using ${sourceObjectName}`, level : "info"},
      M_6A_32_company:  { msg :`${hubName}: Night mode deactivated under duress using ${sourceObjectName}`, level : "info"},
      M_6A_33:  { msg :`${hubName}: arming attempt using ${sourceObjectName} is incomplete`, level : "info"},
      M_6A_34:  { msg :`${hubName}: alarm is temporarily muted using ${sourceObjectName}`, level : "info"},
      M_6A_43:  { msg :`${hubName}: unsuccessful arming attempt using ${sourceObjectName}`, level : "info"},
      M_6D_20:  { msg :`${hubName}: motion detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_23:  { msg :`${hubName}: battery disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_24:  { msg :`${hubName}: battery connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_25:  { msg :`${hubName}: battery low, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_26:  { msg :`${hubName}: battery charged, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_30:  { msg :`${hubName}: connection via Wings channel lost, ${sourceObjectName} in ${sourceRoomName}. You won’t receive photos from this device.`, level : "info"},
      M_6D_31:  { msg :`${hubName}: connection via Wings channel restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_32:  { msg :`${hubName}: received photo on demand, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_33:  { msg :`${hubName}: failed to receive photo on demand, ${sourceObjectName} in ${sourceRoomName}. Please try again.`, level : "info"},
      M_6D_34:  { msg :`${hubName}: received photo by alarm scenario, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_35:  { msg :`${hubName}: failed to receive photo by alarm scenario, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_36:  { msg :`${hubName}: received photo on %4$s’s demand, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6D_37:  { msg :`${hubName}: failed to receive photo on %4$s’s demand, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6E_20:  { msg :`${hubName}: motion detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_00:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_01:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_20:  { msg :`${hubName}: opening detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_21:  { msg :`${hubName}: closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_22:  { msg :`${hubName}: external contact is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_23:  { msg :`${hubName}: external contact closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_24:  { msg :`${hubName}: alarm detected, roller shutter ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_25:  { msg :`${hubName}: roller shutter is disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_26:  { msg :`${hubName}: connection restored, roller shutter ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_30:  { msg :`${hubName}: shock detected by ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_31:  { msg :`${hubName}: tilt detected by ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_34:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_6F_35:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_21:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_22:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_23:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_24:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_25:  { msg :`${hubName}: overheating shutdown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_26:  { msg :`${hubName}: temperature is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_27:  { msg :`${hubName}: enclosure tamper switch disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_28:  { msg :`${hubName}: enclosure tamper switch connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_72_2C:  { msg :`${hubName}: not responding, ${sourceObjectName} in ${sourceRoomName}. Please check the connectivity with the hub.`, level : "info"},
      M_72_2D:  { msg :`${hubName}: ${sourceObjectName} switched on by %4$s`, level : "info"},
      M_72_2F:  { msg :`${hubName}: ${sourceObjectName} switched on, scenario %5$s`, level : "info"},
      M_72_30:  { msg :`${hubName}: ${sourceObjectName} switched on by arming`, level : "info"},
      M_72_31:  { msg :`${hubName}: ${sourceObjectName} switched on by disarming`, level : "info"},
      M_72_32:  { msg :`${hubName}: ${sourceObjectName} switched on`, level : "info"},
      M_72_33:  { msg :`${hubName}: ${sourceObjectName} switched off by %4$s`, level : "info"},
      M_72_35:  { msg :`${hubName}: ${sourceObjectName} switched off, scenario %5$s`, level : "info"},
      M_72_36:  { msg :`${hubName}: ${sourceObjectName} switched off automatically on timer`, level : "info"},
      M_72_37:  { msg :`${hubName}: ${sourceObjectName} switched off by arming`, level : "info"},
      M_72_38:  { msg :`${hubName}: ${sourceObjectName} switched off by disarming`, level : "info"},
      M_72_39:  { msg :`${hubName}: ${sourceObjectName} switched off`, level : "info"},
      M_74_00:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_01:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_20:  { msg :`${hubName}: device was moved, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_21:  { msg :`${hubName}: external power failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_22:  { msg :`${hubName}: external power restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_23:  { msg :`${hubName}: battery disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_24:  { msg :`${hubName}: battery connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_25:  { msg :`${hubName}: battery low, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_26:  { msg :`${hubName}: battery charged, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_34:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_74_35:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_21:  { msg :`${hubName}: front lid open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_22:  { msg :`${hubName}: front lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_23:  { msg :`${hubName}: device detached from surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_24:  { msg :`${hubName}: device fastened back to surface, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_25:  { msg :`${hubName}: short-circuit failure on the output line, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_26:  { msg :`${hubName}: output line restored after a short circuit, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_27:  { msg :`${hubName}: enclosure tamper switch disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_28:  { msg :`${hubName}: enclosure tamper switch connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_29:  { msg :`${hubName}: signal lines overvoltage failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_30:  { msg :`${hubName}: signal lines restored after overvoltage failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_31:  { msg :`${hubName}: output line sabotage detected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_32:  { msg :`${hubName}: output line restored after sabotage, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_76_33:  { msg :`${hubName}: device fuses are blown, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7B_20:  { msg :`${hubName}: device was moved, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7B_21:  { msg :`${hubName}: external power failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7B_22:  { msg :`${hubName}: external power restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_0E:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_0F:  { msg :`${hubName}: deactivated automatically by the expiration of the restore timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_20:  { msg :`${hubName}: external power has been disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_21:  { msg :`${hubName}: external power has been restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_22:  { msg :`${hubName}: battery has been disconnected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_23:  { msg :`${hubName}: battery has been connected, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_24:  { msg :`${hubName}: power supply terminal for detectors is shorted out, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_25:  { msg :`${hubName}: detectors power supply has been restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_26:  { msg :`${hubName}: fire detector power supply terminal is shorted out, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_27:  { msg :`${hubName}: fire detector power supply has been restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_28:  { msg :`${hubName}: battery low, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_7C_29:  { msg :`${hubName}: battery charged, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_00:  { msg :`${hubName}: lid is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_01:  { msg :`${hubName}: lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_02:  { msg :`${hubName}: battery charge is OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_03:  { msg :`${hubName}: low battery, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_04:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is offline. Connection via Jeweller channel lost.`, level : "info"},
      M_ABS_05:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is online again. Connection via Jeweller channel restored.`, level : "info"},
      M_ABS_06:  { msg :`${hubName}: synchronization failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_07:  { msg :`${hubName}: synchronization OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_08:  { msg :`${hubName}: device ${sourceObjectName} added successfully`, level : "info"},
      M_ABS_09:  { msg :`${hubName}: device ${sourceObjectName} removed`, level : "info"},
      M_ABS_0A:  { msg :`${hubName}: device deactivated, ${sourceObjectName} in ${sourceRoomName}. The device will neither execute commands of the system nor notify about alarms or any other events.`, level : "info"},
      M_ABS_0B:  { msg :`${hubName}: the device is active again, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_0C:  { msg :`${hubName}: notifications about the state of the lid are disabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_0D:  { msg :`${hubName}: notifications about the state of the lid are enabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_0E:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_0F:  { msg :`${hubName}: deactivated automatically by the expiration of the restoration timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_10:  { msg :`Updating your ${sourceObjectName} firmware`, level : "info"},
      M_ABS_11:  { msg :`${sourceObjectName} firmware updated successfully`, level : "info"},
      M_ABS_12:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} has detected a malfunction`, level : "info"},
      M_ABS_13:  { msg :`${sourceObjectName} turned off`, level : "info"},
      M_ABS_14:  { msg :`${hubName}: restored after auto deactivation, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_16:  { msg :`${hubName}: device reached its end of service life, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_17:  { msg :`${hubName}: device firmware update launched by %4$s, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_18:  { msg :`${hubName}: failed to update firmware, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_ABS_19:  { msg :`${hubName}: firmware updated successfully, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_00:  { msg :`${hubName}: lid is open, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_01:  { msg :`${hubName}: lid closed, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_02:  { msg :`${hubName}: power voltage restored, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_03:  { msg :`${hubName}: insufficient power voltage, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_04:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is offline. Connection via Fibra channel lost.`, level : "info"},
      M_FCP_05:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is online again. Connection via Fibra channel restored.`, level : "info"},
      M_FCP_06:  { msg :`${hubName}: synchronization failure, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_07:  { msg :`${hubName}: synchronization OK, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_08:  { msg :`${hubName}: device ${sourceObjectName} added successfully`, level : "info"},
      M_FCP_09:  { msg :`${hubName}: device ${sourceObjectName} removed`, level : "info"},
      M_FCP_0A:  { msg :`${hubName}: device deactivated, ${sourceObjectName} in ${sourceRoomName}. The device will neither execute commands of the system nor notify about alarms or any other events.`, level : "info"},
      M_FCP_0B:  { msg :`${hubName}: the device is active again, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_0C:  { msg :`${hubName}: notifications about the state of the lid are disabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_0D:  { msg :`${hubName}: notifications about the state of the lid are enabled, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_0E:  { msg :`${hubName}: deactivated automatically due to max number of alarms, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_0F:  { msg :`${hubName}: deactivated automatically by the expiration of the restoration timer, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      M_FCP_10:  { msg :`Updating your ${sourceObjectName} firmware`, level : "info"},
      M_FCP_11:  { msg :`${sourceObjectName} firmware updated successfully`, level : "info"},
      M_FCP_12:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} has detected a malfunction`, level : "info"},
      M_FCP_13:  { msg :`${sourceObjectName} turned off`, level : "info"},
      M_FCP_14:  { msg :`${hubName}: restored after auto deactivation, ${sourceObjectName} in ${sourceRoomName}`, level : "info"},
      custom_event_descr:  { msg :`If Custom is selected, the event won’t be sent to security company, neither will you receive SMS of its triggering`, level : "info"},
      login_account_alert:  { msg :`New login into account detected`, level : "info"},
      mtr_wi_offline:  { msg :`${hubName}: ${sourceObjectName} in ${sourceRoomName} is offline`, level : "info"},
      pro_access_permanent_request:  { msg :`${sourceObjectName} (%4$s) has requested permanent access to the hub settings`, level : "info"},
      pro_access_permanent_response:  { msg :`${sourceRoomName} has allowed permanent access to the hub settings`, level : "info"},
      pro_access_request:  { msg :`${sourceObjectName} (%4$s) has requested access to the hub settings for {hubName} hours`, level : "info"},
      pro_access_response:  { msg :`${sourceRoomName} granted the access to hub settings for {hubName} hours`, level : "info"},
      pro_access_response_rejected:  { msg :`${sourceRoomName} has denied access to the hub settings`, level : "info"},
      service_company_access_request:  { msg :`Installation company ${sourceObjectName} ({hubName}) requested access to hub settings for ${sourceRoomName} h.`, level : "info"},
      service_company_permanent_access_request:  { msg :`Installation company ${sourceObjectName} ({hubName}) requested permanent access to hub settings`, level : "info"},
    };
  
    if (eventCode in messages) {
      return messages[eventCode];
    } else {
      return `Unknown code: ${eventCode}`;
    }
  }

  export default DecodeMsg;